site_name: The DTW package
theme: cinder
nav:
  - Home: index.md
  - R: r.md
  - Python: python.md
  - FAQ: faq.md
copyright: 'DTW is &copy; 2006-2019, distributed under the <a href="https://cran.r-project.org/web/licenses/GPL-3">GPLv3 license terms</a>.'
markdown_extensions:
  - admonition
  